### ISSUE TITLE
Unit testing options

### ISSUE THREAD

**Issue by apipersenia** [aws-samples/aws-cloudhsm-jce-examples#11]
Hi,
are there any hsm in-memory mocks available that I can use for building out my test suite? 

Thanks!
adi

**Comment by rday** [comment]
At this time there are no officially supported in-memory HSMs that can be used for testing. However, this question would be better asked on the [forums](https://forums.aws.amazon.com/forum.jspa?forumID=156). That will give the question better visibility for other customers and other AWS folks.

Thanks!
