### ISSUE TITLE
Util.findKey() deprecated

### ISSUE THREAD

**Issue by ArtemShypotilov** [aws-samples/aws-cloudhsm-jce-examples#32]
Hi Guys!

Can you please advise why com.cavium.cfm2.Util.findKey() is deprecated?

What should I use instead to get key handle by key label?

Thanks.

**Comment by mayankambaliya** [comment]
You could use KeyStore's getKey function to get a CaviumKey object and call getHandle() on it. 
You can find the example usage in KeyStoreExampleRunner.java or CloudHSMKeyStoreExampleRunner.java

**Comment by rday** [comment]
I'll close this as the sample gives a way to get the handle from the KeyStore, please re-open if there is still an issue!
