### ISSUE TITLE
LoginManger dependency on log4j

### ISSUE THREAD

**Issue by prakashtanaji** [aws-samples/aws-cloudhsm-jce-examples#40]
I am getting the below bean creation failure as the cavium LoginManager is unable to find reference to log4j.LogManager. 

```
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
...

  | Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
  |     at com.cavium.cfm2.LoginManager.<clinit>(LoginManager.java:172)
```

I checked that I have the log4j available. We use slf4j as the logging wrapper, but dont think that will cause an issue.

This happens during the deployment time when the service starts. 
I also made sure that the log4j-core-2.9.1.jar exists in our deployment .war file.

Is it possible that LoginManager has very strong dependency on one particlar ver. of log4j?

**Comment by rday** [comment]
I'm closing this out because of the software updates which should address the issue.

Please re-open if there is still a problem.
