### ISSUE TITLE
Library docs

### ISSUE THREAD

**Issue by mc-sunw** [aws-samples/aws-cloudhsm-jce-examples#51]
Any source or docs, ideally Javadoc, available for the cloudhsm library?  For example, I want to do the equivalent of 'findKey -t key_type', which I assume can be done with the Util.findKeys(String, int, int, int, byte[], Vector) method or similar but it's impossible to know what those parameters actually are although one of those ints is presumably the type.  Similarly with other parts of the API, it's not clear what some of the methods do and what they take.

Specific points I'm trying to figure out:
1. How to find keys based on type (AES, EC etc.), class etc..
2. How to find all keys (Util.findAllKeys(null) does that return everything?).

**Comment by rday** [comment]
Hi @mc-sunw , sorry for the long wait on this one. We have Javadocs available for download on our main [client download page](https://docs.aws.amazon.com/cloudhsm/latest/userguide/client-history.html#client-version-5-9-0).

We have [a sample available](https://github.com/aws-samples/aws-cloudhsm-jce-examples/blob/sdk5/src/main/java/com/amazonaws/cloudhsm/examples/KeyUtilitiesRunner.java#L205-L223) which could help you locate keys by label and by key type.

At this time, our JCE does not have an option to load all keys however.
