### ISSUE TITLE
X.509 certificate format not supported in SDK 5

### ISSUE THREAD

**Issue by DukeDavis12** [aws-samples/aws-cloudhsm-jce-examples#54]
When trying to generate x509 certificate; I am getting the following error: `java. security.NoSuchAlgorithmException: no such algorithm: X.509 for provider CloudHSM `

**Comment by DukeDavis12** [comment]
Use x509 instead of X.509.

**Comment by rday** [comment]
Looks like this is resolved, reopen if not, thanks!
