### ISSUE TITLE
Unable find the generated key in AWS cloud HSM

### ISSUE THREAD

**Issue by konu27** [aws-samples/aws-cloudhsm-jce-examples#75]
Ran the following command from the JCE Provider:
 java -jar key-utility-runner.jar --import-key
output: 
[cloudhsm_provider::hsm1::session::key_management::provider_key_builder::create_key_internal] Key created on the HSM with handle: **655385(0x000A0019)**

command: 
java -jar key-utility-runner.jar --label Test --get-key
output:
Could not find the given key label Test

 unable to find the key from AWS CLI also
 Command:  findKey

        Total number of keys present: 18

        Number of matching keys from start index 0::17

        **Handles of matching keys:
        6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 524305, 524306, 524307, 524308,
        524309, 524310, 524311**

        Cluster Status:
        Node id 2 status: 0x00000000 : HSM Return: SUCCESS

        Cfm3FindKey returned: 0x00 : HSM Return: SUCCESS

**Comment by tstiemerling** [comment]
Is the key a token key (persistent) or session key (transient)? You will only see it if its a token key and it looks like the sample code does not set the token attribute.

**Comment by rday** [comment]
We don't set the token attribute in our samples to prevent filling up customer HSMs while they are just testing. This is probably the issue, so closing this out. Please re-open if needed!
