### ISSUE TITLE
Specify setting CU username and password in running examples section

### ISSUE THREAD

**Issue by tstiemerling** [aws-samples/aws-cloudhsm-jce-examples#77]
In the "Running and verifying all the samples" specify that the CU username and password should be set before running samples:

export HSM_USER=<cu_username>
export HSM_PASSWORD=<cu_password>

or

java -DHSM_USER=<cu_username> -DHSM_PASSWORD=<cu_password> ...

See also issue #3 and #68

**Comment by rday** [comment]
Updated readme in c57ad1b . Leaving other issues open for specific sample modifications.
