### ISSUE TITLE
Import EC Key Issue

### ISSUE THREAD

**Issue by narasimhaks** [aws-samples/aws-cloudhsm-jce-examples#78]
Hi, 

I am trying to import an EC Private Key using the Keystore.SetKeyEntry() method. But the key is not being persistent. Can you please provide samples of setting the key attributes for keystore examples?

Alternatively is there a way to generate an EC Private key with curve params EC_CURVE_SECP521 and a custom point on the curve? Right now if i specify an EC_POINT attribute i am getting an AddAttributeException with an Unsupported Attribute error.

Please advice.

Thanks
Narasimha

**Comment by rday** [comment]
There is a sample available as of #79. I hope this helps, thanks!

**Comment by narasimhaks** [comment]
Thanks, That solves my issue.
