### ISSUE TITLE
java.security.NoSuchAlgorithmException: no such algorithm: ECDH for provider CloudHSM

### ISSUE THREAD

**Issue by weiqiangredtea** [aws-samples/aws-cloudhsm-jce-examples#84]
java.security.NoSuchAlgorithmException: no such algorithm: ECDH for provider CloudHSM    happened
When I use CloudHSM(cloudhsm-jce-5.11.0.jar) with Algorithm：ECDH 
code：KeyAgreement keyAgree = KeyAgreement.getInstance("ECDH", CloudHsmProvider.PROVIDER_NAME);

![image](https://github.com/aws-samples/aws-cloudhsm-jce-examples/assets/103087216/556b854c-ac25-4f78-b736-994483973ebb)
So how should I solve this problem?

**Comment by weiqiangredtea** [comment]
@rday @jpeddicord @TheEmpty @hyandell 
I urgently need your reply. thanks~

**Comment by rday** [comment]
Hi @weiqiangredtea , 

Please see https://docs.aws.amazon.com/cloudhsm/latest/userguide/ki-pkcs11-sdk.html#ki-pkcs11-9 for some additional information on ECDH. There are possible security concerns, depending on how you use the key. Are you able to work with a TAM who could involve a security specialist to dive deeper into your use case?

**Comment by rday** [comment]
Closing as we can't move forward without more information. Please re-open if needed!
